apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: power-jobs
  namespace: git-events-runner
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
      - configmaps
      - services
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: power-jobs
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: power-jobs
  namespace: git-events-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: power-jobs
subjects:
  - kind: ServiceAccount
    name: git-events-runner-action-job
    namespace: git-events-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: power-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: power-jobs
subjects:
  - kind: ServiceAccount
    name: git-events-runner-action-job
    namespace: git-events-runner
