apiVersion: git-events-runner.rs/v1alpha1
kind: WebhookTrigger
metadata:
  name: git-events-runner-trigger
  namespace: git-events-runner
spec:
  sources:
    kind: GitRepo
    names:
      - git-events-runner-repo
    watchOn:
      onChangeOnly: false # trigger action regardless of changes
      reference:
        tag: v0.1.0
  webhook:
    multiSource: false
    authConfig:
      secretRef:
        name: webhook-auth
      key: token
  action:
    kind: Action
    name: upgrade-controller
