[package]
authors = ["Oleksii Karpenko <alexkarpenko@yahoo.com>"]
description = "Kubernetes operator to run Jobs on events from Git"
edition = "2021"
rust-version = "1.81"
keywords = ["kubernetes", "operator", "git", "events", "runner"]
license = "MIT"
name = "git-events-runner"
repository = "https://github.com/alex-karpenko/git-events-runner"
version = "0.2.4"

[[bin]]
doc = false
name = "git-events-runner"
path = "src/bin/git-events-runner.rs"

[[bin]]
doc = false
name = "gitrepo-cloner"
path = "src/bin/gitrepo-cloner.rs"

[dependencies]
anyhow = "1.0.89"
axum = { version = "0.7.5", default-features = false, features = [
    "http1",
    "macros",
    "matched-path",
    "original-uri",
    "tokio",
    "tracing",
    "tower-log",
    "json",
] }
chrono = { version = "0.4.38", default-features = false, features = ["std"] }
clap = { version = "4.5.17", features = ["derive"] }
futures = "0.3.30"
git2 = "0.19.0"
globwalk = "0.9.1"
hex = "0.4.3"
humantime = "2.1.0"
k8s-openapi = { version = "0.23.0", features = ["v1_27", "schemars"] }
kube = { version = "0.95.0", features = [
    "runtime",
    "client",
    "derive",
    "unstable-runtime",
] }
kube-lease-manager = { version = "0.4.0" }
rand = "0.8.5"
rustls = { version = "0.23.13", features = [
    "std",
    "ring",
], default-features = false }
rustls-native-certs = "0.8.0"
rustls-pemfile = "2.1.3"
sacs = { version = "0.6.3", features = ["async-trait"] }
schemars = "0.8.21"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
    "sync",
] }
tonic = { version = "0.12.2" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
opentelemetry = { version = "0.24.0", features = ["trace", "logs"] }
opentelemetry_sdk = { version = "0.24.1", features = ["rt-tokio", "tokio"] }
opentelemetry-otlp = { version = "0.17.0", features = [
    "tokio",
    "trace",
    "tonic",
    "grpc-tonic",
] }
tracing-opentelemetry = "0.25.0"
uuid = { version = "1.10.0", features = ["v4"] }
prometheus = { version = "0.13.4", default-features = false }

[dev-dependencies]
insta = { version = "1.40.0", features = [
    "glob",
    "ron",
    "redactions",
    "filters",
    "yaml",
] }
tempfile = "3.12.0"
