[package]
authors = ["Oleksii Karpenko <alexkarpenko@yahoo.com>"]
description = "Kubernetes operator to run Jobs on events from Git"
edition = "2021"
keywords = [
    "kubernetes",
    "k8s",
    "kube",
    "operator",
    "controller",
    "git",
    "events",
    "runner",
    "job",
]
license = "MIT OR Apache-2.0"
name = "git-events-runner"
repository = "https://github.com/alex-karpenko/git-events-runner"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
doc = false
name = "git-events-runner"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[[bin]]
doc = false
name = "gitrepo-cloner"
path = "src/gitrepo-cloner.rs"

[lib]
name = "controllers"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
axum = { version = "0.7.5", default-features = false, features = [
    "http1",
    "matched-path",
    "original-uri",
    "tokio",
    "tracing",
    "tower-log",
    "json",
] }
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
git2 = "0.18.3"
humantime = "2.1.0"
k8s-openapi = { version = "0.21.1", features = ["v1_27"] }
kube = { version = "0.90.0", features = ["runtime", "client", "derive"] }
kubert = { version = "0.21.1", features = ["lease"], default-features = false }
kubert-k8s-openapi = { package = "k8s-openapi", version = "0.20.0", features = [
    "v1_27",
] }
kubert-kube = { package = "kube", version = "0.87.1", features = ["client"] }
rand = "0.8.5"
rustls = { version = "0.23.4", features = [
    "std",
    "ring",
], default-features = false }
rustls-native-certs = "0.7.0"
rustls-pemfile = "2.1.1"
sacs = { git = "https://github.com/alex-karpenko/sacs.git", version = "0.3.0", features = [
    "async-trait",
] }
schemars = "0.8.16"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.33"
sha2 = "0.10.8"
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
thiserror = "1"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
    "sync",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
uuid = { version = "1.8.0", features = ["v4"] }
