[package]
authors = ["Oleksii Karpenko <alexkarpenko@yahoo.com>"]
description = "Kubernetes operator to run Jobs on events from Git"
edition = "2024"
rust-version = "1.89"
keywords = ["kubernetes", "operator", "git", "events", "runner"]
license = "MIT"
name = "git-events-runner"
repository = "https://github.com/alex-karpenko/git-events-runner"
version = "0.4.7"

[[bin]]
doc = false
name = "git-events-runner"
path = "src/bin/git-events-runner.rs"

[[bin]]
doc = false
name = "gitrepo-cloner"
path = "src/bin/gitrepo-cloner.rs"

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", default-features = false, features = [
    "http1",
    "macros",
    "matched-path",
    "original-uri",
    "tokio",
    "tracing",
    "tower-log",
    "json",
] }
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
chrono = { version = "0.4.41", default-features = false, features = ["std"] }
clap = { version = "4.5.40", features = ["derive"] }
futures = "0.3.31"
git2 = "0.20.2"
globwalk = "0.9.1"
hex = "0.4.3"
humantime = "2.2.0"
k8s-openapi = { version = "0.26.0", features = ["v1_30", "schemars"] }
kube = { version = "2.0.0", features = ["runtime", "client", "derive", "unstable-runtime"] }
kube-lease-manager = { version = "0.10.0" }
rand = "0.9.2"
rustls = { version = "0.23.28", features = ["std", "tls12", "aws-lc-rs"], default-features = false }
rustls-native-certs = "0.8.1"
rustls-pemfile = "2.2.0"
sacs = { version = "0.8.2", features = ["async-trait", "tz"] }
schemars = "1.0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml_ng = "0.10.0"
sha2 = "0.10.9"
strum = { version = "0.27.1", features = ["derive"] }
strum_macros = "0.27.1"
thiserror = "2.0.16"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread", "fs", "io-util", "sync"] }
tonic = { version = "0.14.2" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
opentelemetry = { version = "0.30.0", features = ["trace", "logs"] }
opentelemetry_sdk = { version = "0.30.0", features = ["rt-tokio", "tokio"] }
opentelemetry-otlp = { version = "0.30.0", features = ["tokio", "trace", "tonic", "grpc-tonic"] }
tracing-opentelemetry = "0.31.0"
uuid = { version = "1.17.0", features = ["v4"] }
prometheus = { version = "0.14.0", default-features = false }
tower_governor = { version = "0.7.0", features = ["tracing"] }

[dev-dependencies]
base64 = "0.22.1"
ctor = "0.5.0"
insta = { version = "1.43.1", features = ["glob", "ron", "redactions", "filters", "yaml"] }
rstest = "0.26.1"
rstest_reuse = "0.7.0"
tempfile = "3.20.0"
testcontainers = { version = "0.25.0", default-features = false }
testcontainers-modules = { version = "0.13.0", default-features = false, features = ["gitea"] }

[build-dependencies]
anyhow = "1.0.98"
