[package]
authors = ["Oleksii Karpenko <alexkarpenko@yahoo.com>"]
description = "Kubernetes operator to run Jobs on events from Git"
edition = "2021"
rust-version = "1.81"
keywords = ["kubernetes", "operator", "git", "events", "runner"]
license = "MIT"
name = "git-events-runner"
repository = "https://github.com/alex-karpenko/git-events-runner"
version = "0.4.2"

[[bin]]
doc = false
name = "git-events-runner"
path = "src/bin/git-events-runner.rs"

[[bin]]
doc = false
name = "gitrepo-cloner"
path = "src/bin/gitrepo-cloner.rs"

[dependencies]
anyhow = "1.0.95"
axum = { version = "0.8.1", default-features = false, features = [
    "http1",
    "macros",
    "matched-path",
    "original-uri",
    "tokio",
    "tracing",
    "tower-log",
    "json",
] }
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
chrono = { version = "0.4.39", default-features = false, features = ["std"] }
clap = { version = "4.5.23", features = ["derive"] }
futures = "0.3.31"
git2 = "0.20.0"
globwalk = "0.9.1"
hex = "0.4.3"
humantime = "2.1.0"
k8s-openapi = { version = "0.24.0", features = ["v1_28", "schemars"] }
kube = { version = "0.99.0", features = ["runtime", "client", "derive", "unstable-runtime"] }
kube-lease-manager = { version = "0.8.0" }
rand = "0.9.0"
rustls = { version = "0.23.20", features = ["std", "tls12", "aws-lc-rs"], default-features = false }
rustls-native-certs = "0.8.1"
rustls-pemfile = "2.2.0"
sacs = { version = "0.8.0", features = ["async-trait", "tz"] }
schemars = "0.8.21"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
strum = { version = "0.27.0", features = ["derive"] }
strum_macros = "0.27.0"
thiserror = "2.0.12"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "fs", "io-util", "sync"] }
tonic = { version = "0.13.0" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
opentelemetry = { version = "0.29.0", features = ["trace", "logs"] }
opentelemetry_sdk = { version = "0.29.0", features = ["rt-tokio", "tokio"] }
opentelemetry-otlp = { version = "0.29.0", features = ["tokio", "trace", "tonic", "grpc-tonic"] }
tracing-opentelemetry = "0.30.0"
uuid = { version = "1.11.0", features = ["v4"] }
prometheus = { version = "0.14.0", default-features = false }
tower_governor = { version = "0.7.0", features = ["tracing"] }

[dev-dependencies]
base64 = "0.22.1"
ctor = "0.4.1"
insta = { version = "1.41.1", features = ["glob", "ron", "redactions", "filters", "yaml"] }
rstest = "0.25.0"
rstest_reuse = "0.7.0"
tempfile = "3.15.0"
testcontainers = { version = "0.23.1", default-features = false }
testcontainers-modules = { version = "0.11.4", default-features = false, features = ["gitea"] }

[build-dependencies]
anyhow = "1.0.95"
