[package]
authors = ["Oleksii Karpenko <alexkarpenko@yahoo.com>"]
description = "Kubernetes operator to run Jobs on events from Git"
edition = "2021"
rust-version = "1.75"
keywords = ["kubernetes", "operator", "git", "events", "runner"]
license = "MIT"
name = "git-events-runner"
repository = "https://github.com/alex-karpenko/git-events-runner"
version = "0.2.1"

[[bin]]
doc = false
name = "git-events-runner"
path = "src/bin/git-events-runner.rs"

[[bin]]
doc = false
name = "gitrepo-cloner"
path = "src/bin/gitrepo-cloner.rs"

[dependencies]
anyhow = "1.0.83"
axum = { version = "0.7.5", default-features = false, features = [
    "http1",
    "macros",
    "matched-path",
    "original-uri",
    "tokio",
    "tracing",
    "tower-log",
    "json",
] }
chrono = { version = "0.4.38", default-features = false, features = ["std"] }
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
git2 = "0.19.0"
globwalk = "0.9.1"
hex = "0.4.3"
humantime = "2.1.0"
k8s-openapi = { version = "0.22.0", features = ["v1_27", "schemars"] }
kube = { version = "0.92.0", features = [
    "runtime",
    "client",
    "derive",
    "unstable-runtime",
] }
kubert = { version = "0.21.2", features = ["lease"], default-features = false }
kubert-k8s-openapi = { package = "k8s-openapi", version = "0.20.0", features = [
    "v1_27",
] }
kubert-kube = { package = "kube", version = "0.87.2", features = ["client"] }
rand = "0.8.5"
rustls = { version = "0.23.5", features = [
    "std",
    "ring",
], default-features = false }
rustls-native-certs = "0.7.0"
rustls-pemfile = "2.1.2"
sacs = { version = "0.6.0", features = ["async-trait"] }
# sacs = { version = "0.6.0", git = "https://github.com/alex-karpenko/sacs.git", branch = "rel-v0.6" }
schemars = "0.8.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.116"
serde_yaml = "0.9.33"
sha2 = "0.10.8"
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
thiserror = "1.0.60"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
    "sync",
] }
tonic = { version = "0.11.0" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
opentelemetry = { version = "0.23.0", features = ["trace", "logs"] }
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio", "tokio"] }
opentelemetry-otlp = { version = "0.16.0", features = [
    "tokio",
    "trace",
    "tonic",
    "grpc-tonic",
] }
tracing-opentelemetry = "0.24.0"
uuid = { version = "1.8.0", features = ["v4"] }


[dev-dependencies]
insta = { version = "1", features = [
    "glob",
    "ron",
    "redactions",
    "filters",
    "yaml",
] }
tempdir = "0.3.7"
