site_name: Git Events Runner
site_author: Oleksii Karpenko
repo_name: git-events-runner
remote_branch: gh-pages
copyright: Copyright &copy; 2024 Oleksii Karpenko
site_url: https://alex-karpenko.github.io/git-events-runner/
repo_url: https://github.com/alex-karpenko/git-events-runner

plugins:
  - mike:

extra:
  version:
    provider: mike
    alias: true
    default:
      - latest

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tooltips
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Light mode

markdown_extensions:
  - pymdownx.betterem
  - pymdownx.snippets
  - toc:
      permalink: true
      title: On this page
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Introduction:
      - Introduction: index.md
      - Overview: intro/overview.md
      - Quick start: intro/quick-start.md
      - Current state: intro/state.md
      - License: lic.md
  - Guides:
      - Core concepts: guides/concepts.md
      - Installation: guides/install.md
      - Configuration: guides/config.md
      - Resources:
          - Sources: resources/sources.md
          - Triggers: resources/triggers.md
          - Actions: resources/actions.md
      - Observability: guides/observability.md
  - Development:
      - Changelog: changelog.md
      - Roadmap: roadmap.md
      - Bugs: bugs.md
