apiVersion: git-events-runner.rs/v1alpha1
kind: ScheduleTrigger
metadata:
  name: trigger-example
  namespace: default
spec:
  # Mandatory section,
  # It specifies a list of the sources to watch and optionally watching config
  sources:
    # Kind of the sources,
    # Allowed values: GitRepo and ClusterGitRepo
    kind: GitRepo
    # List of the sources to watch on. Trigger will clone each repo one by one,
    # and check for changes each repo separately.
    #
    # Trigger calls action for each source separately,
    # so if all three sources (in the example below) were changed -
    # trigger calls action three times consecutively.
    names:
      - source-repo-1
      - source-repo-2
      - source-repo-3
    # Optional watching config
    watchOn:
      # Run action if repo reference was changes only,
      # and ignore it if the current commit is the same
      # as during the previous run.
      #
      # If this field is `false`, trigger will call action each time
      # it runs regardless of changes in the source.
      #
      # Default is `true`
      onChangeOnly: true
      # Which referent to watch on
      # Allowed keys: branch, tag and commit with corresponding values.
      # These keys are mutually exclusive.
      # Default is `branch: main`
      reference:
        branch: main # default
        tag: v0.1.0
        commit: 92abcd3fc4082ed5e53f12b383e14580b83dcff3
      # Optionally, besides checking for changes in the whole repo,
      # trigger can check for changes in some particular file.
      # Hash of the file matters, but modification time doesn't.
      #
      # Logic for calling action is:
      # - if both reference and file were changed/add/removed - call the action,
      # - if reference was changed, but the file wasn't - don't call the cation,
      # - if reference was changed, but the file isn't present - call the action.
      file: doc/examples/scheduletrigger.yaml

  schedule:
    interval: 1m
    cron: "*/15 9-20 * * 1-5"

  action:
    kind: Action
    name: some-action
