apiVersion: git-events-runner.rs/v1alpha1
kind: ScheduleTrigger
metadata:
  name: git-events-runner-trigger
  namespace: git-events-runner
spec:
  sources:
    kind: GitRepo
    names:
      - git-events-runner-repo
    watchOn:
      onChangeOnly: true # trigger action if repo changed only
      reference:
        branch: main
  schedule:
    interval: 1h
  action:
    kind: Action
    name: upgrade-controller
