apiVersion: v1
kind: Service
metadata:
  name: {{ include "git-events-runner.fullname" . }}
  labels:
    {{- include "git-events-runner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.utility }}
      targetPort: utility
      protocol: TCP
      name: utility
    - port: {{ .Values.service.webhook }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "git-events-runner.selectorLabels" . | nindent 4 }}
