name: Continuous integration
on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Build
        run: cargo build

      - name: Test
        env:
          CI: true
        run: cargo test

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

  docker-test:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      matrix:
        binary:
          - git-events-runner
          - gitrepo-cloner
          - action-worker
    steps:
      - uses: actions/checkout@v4
      - name: Test image build
        run: docker build -f docker-build/${{matrix.binary}}.dockerfile .

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint helm charts
        run: |
          for c in `find charts -type d -depth 1`; do
            helm lint charts/${c}
          done
